version: '3'

services:
  database-auth:
    image: mysql:8.0.30-debian
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms-auth
    networks:
      - lms

  database-faculty:
    image: mysql:8.0.30-debian
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms-faculty
    networks:
      - lms

  database-subject:
    image: mysql:8.0.30-debian
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms-subject
    networks:
      - lms

  database-exam:
    image: mysql:8.0.30-debian
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms-exam
    networks:
      - lms

  backend-config-server:
    build:
      context: ./backend/config-server
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    environment:
      SPRING_PROFILES_ACTIVE: prod, native
    networks:
      - lms

  backend-discovery-server:
    build:
      context: ./backend/discovery-server
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - lms

  backend-api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend-discovery-server
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - lms

  backend-auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - backend-discovery-server
      - database-auth
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - lms

  backend-faculty-service:
    build:
      context: ./backend/faculty-service
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - backend-discovery-server
      - database-faculty
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - lms

  backend-subject-service:
    build:
      context: ./backend/subject-service
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    depends_on:
      - backend-discovery-server
      - database-subject
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - lms

  backend-exam-service:
    build:
      context: ./backend/exam-service
      dockerfile: Dockerfile
    ports:
      - 8084:8084
    depends_on:
      - backend-discovery-server
      - database-exam
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - lms

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      PRODUCTION: true
    networks:
      - lms

networks:
  lms:
    driver: bridge
