spring:
  application:
    name: discovery-server
  eureka:
    client:
      service-url:
      defaultZone: http://localhost:8761/eureka/ # replace ${EUREKA_SERVER_IP} and ${PORT} with actual values
      fetch-registry: false
      register-with-eureka: false
  config:
    import: optional:configserver:http://localhost:8888